name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} # GitHub PAT
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "${{ github.repository_owner }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build . -f Dockerfile -t "${{ github.repository_owner }}/maintenance-page:latest"

      - name: Push Docker image
        run: |
          docker push "${{ github.repository_owner }}/maintenance-page:latest"
